// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZeuQH_Kneo5-ptaG3fjmTwGUOgp7TKCU',
    appId: '1:721100205456:web:7453a308c4099671be5715',
    messagingSenderId: '721100205456',
    projectId: 'crudtutorial-2c497',
    authDomain: 'crudtutorial-2c497.firebaseapp.com',
    storageBucket: 'crudtutorial-2c497.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd37l-Q-poVEsDOgpW510nOuCqXoScG74',
    appId: '1:721100205456:android:9e8401eef8750550be5715',
    messagingSenderId: '721100205456',
    projectId: 'crudtutorial-2c497',
    storageBucket: 'crudtutorial-2c497.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7TcLUZpl9E8dL6Sgkr-Uk8FKqa1-Nqj8',
    appId: '1:721100205456:ios:8e1c98c615922215be5715',
    messagingSenderId: '721100205456',
    projectId: 'crudtutorial-2c497',
    storageBucket: 'crudtutorial-2c497.appspot.com',
    iosBundleId: 'com.example.crudtutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7TcLUZpl9E8dL6Sgkr-Uk8FKqa1-Nqj8',
    appId: '1:721100205456:ios:8e1c98c615922215be5715',
    messagingSenderId: '721100205456',
    projectId: 'crudtutorial-2c497',
    storageBucket: 'crudtutorial-2c497.appspot.com',
    iosBundleId: 'com.example.crudtutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZeuQH_Kneo5-ptaG3fjmTwGUOgp7TKCU',
    appId: '1:721100205456:web:678b55d5f3c9938dbe5715',
    messagingSenderId: '721100205456',
    projectId: 'crudtutorial-2c497',
    authDomain: 'crudtutorial-2c497.firebaseapp.com',
    storageBucket: 'crudtutorial-2c497.appspot.com',
  );
}
